version: "3.8"
services:
  redpanda:
    image: redpanda/redpanda:v24.1.4
    command:
      - redpanda
      - start
      - --mode=dev-container
      - --smp=1
      - --memory=1G
      - --overprovisioned
      - --kafka-addr=0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092"
      - "19092:19092"

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      - CLICKHOUSE_DB=viewbot
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    volumes:
      - ./storage/init:/docker-entrypoint-initdb.d
      - ch_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: [clickhouse]
    volumes:
      - gf_data:/var/lib/grafana

  jobmanager:
    image: flink:1.18.1-scala_2.12-java11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    depends_on: [redpanda]

  taskmanager:
    image: flink:1.18.1-scala_2.12-java11
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    depends_on: [jobmanager]

  player:
    image: nginx:1.25-alpine
    volumes:
      - ../player:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

  challenges:
    build:
      context: ../challenges
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "8787:8787"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP=redpanda:9092
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redpanda
      - clickhouse
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ch_data: {}
  gf_data: {}
  redis_data: {}
